import 'package:flutter/material.dart';
import 'package:pharmacy/app/assets.dart';

///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AssetsImage {
  AssetsImage._();

  static Widget appBarBg = Assets.bgAppBarBg.getScaledImage();

  static Widget images404Error = Assets.images404Error.getImage();
  // static Widget imagesCat1Headache = Assets.imagesCat1Headache.getImage();
  static Widget imagesCat2Supplements = Assets.imagesSupplement.getImage();
  static Widget imagesCat3Infants = Assets.imagesInfant.getImage();
  static Widget imagesCat4Cough = Assets.imagesCough.getImage();
  static Widget imagesDoliprane = Assets.imagesDoliprane.getImage();
  static Widget imagesEmzor = Assets.imagesEmzor.getImage();
  static Widget imagesIburofen = Assets.imagesIburofen.getImage();
  static Widget imagesIburophen2 = Assets.imagesIburophen2.getImage();
  static Widget imagesPanadol = Assets.imagesPanadol.getImage();
  static Widget imagesParacetamol = Assets.imagesParacetamol.getImage();
  // static Widget imagesParacetamol2 = Assets.imagesParacetamol2.getImage();
  static Widget imagesParacetamol3 = Assets.imagesParacetamol3.getImage();
  static Widget imagesSupplement = Assets.imagesSupplement.getImage();
  static Widget imagesInfant = Assets.imagesInfant.getImage();
  static Widget imagesCough = Assets.imagesCough.getImage();
  static Widget imagesCat1Headache = Assets.assetsImagesCat1Headache.getImage();
}

extension AssetImageExt on String {
  Widget getImage() {
    return Image.asset(
      this,
      fit: BoxFit.cover,
    );
  }

  Widget getScaledImage() {
    return Image.asset(
      this,
      fit: BoxFit.fill,
    );
  }
}
